### ISSUE TITLE
jupyter-scatter 0.10.0 doesn't work for me

### ISSUE THREAD

**Issue by ekungurov** [flekschas/jupyter-scatter#58]
After upgrading to jupyter-scatter==0.10.0 JupyterLab prints the following error:
```
Error displaying widget: model not found
```
Rolling back to jupyter-scatter==0.9.0 fixes the issue. 
I'm using JupyterLab 3.4.8, jupyterlab_widgets 1.1.1, ipywidgets 7.7.2

**Comment by flekschas** [comment]
Thanks for reporting. I'll investigate

**Comment by flekschas** [comment]
Just checking, did you restart jupyter-lab after updating?

**Comment by ekungurov** [comment]
@flekschas yes

**Comment by flekschas** [comment]
Unfortunately, I cannot reproduce the error. I've tested the fresh installations of v0.10.0 using the following conda environments:

**Python 3.9 with Jupyter Lab v3, ipywidgets v7 and jupyterlab-widgets v1**

```yml
name: jscatter-py39-ipyw7-jlab1

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.9.*
  - numpy
  - pandas
  - pip
  - pip:
    - jupyterlab==3.*
    - ipywidgets==7.*
    - jupyterlab_widgets==1.*
    - jupyter-scatter
```

**Python 3.9 with Jupyter Lab v3, ipywidgets v8 and jupyterlab-widgets v3**

```yml
name: jscatter-py39-ipyw8-jlab3

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.9.*
  - numpy
  - pandas
  - pip
  - pip:
    - jupyterlab==3.*
    - ipywidgets==8.*
    - jupyterlab_widgets==3.*
    - jupyter-scatter
```

**Python 3.10 with Jupyter Lab v3, ipywidgets v7 and jupyterlab-widgets v1**

```yml
name: jscatter-py310-ipyw7-jlab1

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10.*
  - numpy
  - pandas
  - pip
  - pip:
    - jupyterlab==3.*
    - ipywidgets==7.*
    - jupyterlab_widgets==1.*
    - jupyter-scatter
```

**Python 3.10 with Jupyter Lab v3, ipywidgets v8 and jupyterlab-widgets v3**

```yml
name: jscatter-py310-ipyw8-jlab3

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10.*
  - numpy
  - pandas
  - pip
  - pip:
    - jupyterlab==3.*
    - ipywidgets==8.*
    - jupyterlab_widgets==3.*
    - jupyter-scatter
```

When I run the following, everything gets rendered as expected every time:

```py
import numpy as np
import jscatter
jscatter.plot(x=np.random.rand(500), y=np.random.rand(500))
```

(Note, when I restart Jupyter Lab and have not yet re-run the cell, I also see `Error displaying widget: model not found`! This is expected because the widget instance is not preserved across after Jupyter Lab is shut down. You must rerun the cell.)

See [./test-environments](../tree/master/test-environments) for the test environments settings.

Can you provide a complete conda environment that reproduces the issue?

**Comment by ekungurov** [comment]
@flekschas environment is really huge, but it seems that version 0.10 works well with JuptyerLab 3.5.2 and doesn't work with JupyterLab 3.4.8

**Comment by flekschas** [comment]
I still can't reproduce your issue. I've installed jscatter v0.10.0 successfully with JupyterLab 3.4.8, jupyterlab_widgets 1.1.1, ipywidgets 7.7.2 using the following environment:

```yml
name: jscatter-py39-ipyw7-jlab1-test

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.9.*
  - numpy
  - pip
  - pip:
    - jupyterlab==3.4.8
    - ipywidgets==7.7.2
    - jupyterlab_widgets==1.1.1
    - jupyter-scatter
```

And `pip freeze`:

- anyio==3.6.2
- appnope==0.1.3
- argon2-cffi==21.3.0
- argon2-cffi-bindings==21.2.0
- asttokens==2.2.1
- attrs==22.2.0
- Babel==2.11.0
- backcall==0.2.0
- beautifulsoup4==4.11.1
- bleach==5.0.1
- certifi==2022.12.7
- cffi==1.15.1
- charset-normalizer==2.1.1
- comm==0.1.2
- contourpy==1.0.6
- cycler==0.11.0
- debugpy==1.6.5
- decorator==5.1.1
- defusedxml==0.7.1
- deprecation==2.1.0
- entrypoints==0.4
- executing==1.2.0
- fastjsonschema==2.16.2
- fonttools==4.38.0
- idna==3.4
- importlib-metadata==6.0.0
- ipykernel==6.20.1
- ipython==8.8.0
- ipython-genutils==0.2.0
- **_ipywidgets==7.7.2_**
- jedi==0.18.2
- Jinja2==3.1.2
- json5==0.9.11
- jsonschema==4.17.3
- **_jupyter-scatter==0.10.0_**
- jupyter-server==1.23.4
- jupyter_client==7.4.8
- jupyter_core==5.1.3
- jupyter_packaging==0.12.3
- **_jupyterlab==3.4.8_**
- jupyterlab-pygments==0.2.2
- **_jupyterlab-widgets==1.1.1_**
- jupyterlab_server==2.18.0
- kiwisolver==1.4.4
- MarkupSafe==2.1.1
- matplotlib==3.6.3
- matplotlib-inline==0.1.6
- mistune==2.0.4
- nbclassic==0.4.8
- nbclient==0.7.2
- nbconvert==7.2.7
- nbformat==5.7.3
- nest-asyncio==1.5.6
- notebook==6.5.2
- notebook_shim==0.2.2
- numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1672415759761/work
- packaging==23.0
- pandas==1.5.2
- pandocfilters==1.5.0
- parso==0.8.3
- pexpect==4.8.0
- pickleshare==0.7.5
- Pillow==9.4.0
- platformdirs==2.6.2
- prometheus-client==0.15.0
- prompt-toolkit==3.0.36
- psutil==5.9.4
- ptyprocess==0.7.0
- pure-eval==0.2.2
- pycparser==2.21
- Pygments==2.14.0
- pyparsing==3.0.9
- pyrsistent==0.19.3
- python-dateutil==2.8.2
- pytz==2022.7
- pyzmq==25.0.0
- requests==2.28.1
- Send2Trash==1.8.0
- six==1.16.0
- sniffio==1.3.0
- soupsieve==2.3.2.post1
- stack-data==0.6.2
- terminado==0.17.1
- tinycss2==1.2.1
- tomli==2.0.1
- tomlkit==0.11.6
- tornado==6.2
- traitlets==5.8.1
- traittypes==0.2.1
- typing_extensions==4.4.0
- urllib3==1.26.14
- wcwidth==0.2.5
- webencodings==0.5.1
- websocket-client==1.4.2
- widgetsnbextension==3.6.1
- zipp==3.11.0

Unless you can provide a reproducible example, there isn't anything I can do.
